# Generated by Django 4.2.4 on 2023-08-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='коментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='время начала')),
                ('finish_time', models.DateTimeField(verbose_name='время окончания')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'завершена'), (2, 'создана'), (3, 'запушена')], default=2, verbose_name='статус рассылки')),
                ('periodicity', models.PositiveSmallIntegerField(choices=[(1, 'раз в день'), (2, 'раз в неделю'), (3, 'раз в месяц')], default=2, verbose_name='периодичность')),
                ('title_message', models.CharField(blank=True, max_length=200, null=True, verbose_name='тема письма')),
                ('body_message', models.TextField(blank=True, null=True, verbose_name='письмо')),
                ('clients', models.ManyToManyField(to='mailing_list.client', verbose_name='клиенты')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
