# Generated by Django 4.2.4 on 2023-08-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='body_message',
            field=models.TextField(blank=True, null=True, verbose_name='письмо'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='title_message',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='тема письма'),
        ),
        migrations.AlterField(
            model_name='mailinglist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='время рассылки'),
        ),
    ]
