# Generated by Django 4.2.4 on 2023-08-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0002_mailinglist_body_message_mailinglist_title_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='date',
            field=models.DateTimeField(verbose_name='время рассылки'),
        ),
    ]
